name 'regularroutes'
maintainer 'Dinador Ltd'
maintainer_email 'dinador@dinador.com'
license 'MIT'
description 'Installs/Configures the regularroutes server to be used with the TrafficSense family of mobile clients.'
version '0.2.0'

depends 'apt', '~> 7.0.0'
depends 'build-essential', '~> 8.1.1'
depends 'nginx', '~> 8.1.2'
depends 'postgresql_lwrp', '~> 1.4.0'
# depends 'postgis', '~> 0.3.0'
depends 'poise-python', '~> 1.6.0'
depends 'locale', '~> 2.0.1'
